/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo/$moduleId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ModuloModuleIdAulaLessonIdRouteImport } from './routes/modulo/$moduleId.aula.$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdAulaLessonIdRoute =
  ModuloModuleIdAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => ModuloModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRouteWithChildren
  '/modulo/$moduleId/aula/$lessonId': typeof ModuloModuleIdAulaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aulas'
    | '/login'
    | '/admin/users'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aulas'
    | '/login'
    | '/admin/users'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/aulas'
    | '/login'
    | '/admin/users'
    | '/modulo/$moduleId'
    | '/modulo/$moduleId/aula/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRoute
  LoginRoute: typeof LoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId/aula/$lessonId': {
      id: '/modulo/$moduleId/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/modulo/$moduleId/aula/$lessonId'
      preLoaderRoute: typeof ModuloModuleIdAulaLessonIdRouteImport
      parentRoute: typeof ModuloModuleIdRoute
    }
  }
}

interface ModuloModuleIdRouteChildren {
  ModuloModuleIdAulaLessonIdRoute: typeof ModuloModuleIdAulaLessonIdRoute
}

const ModuloModuleIdRouteChildren: ModuloModuleIdRouteChildren = {
  ModuloModuleIdAulaLessonIdRoute: ModuloModuleIdAulaLessonIdRoute,
}

const ModuloModuleIdRouteWithChildren = ModuloModuleIdRoute._addFileChildren(
  ModuloModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRoute,
  LoginRoute: LoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  ModuloModuleIdRoute: ModuloModuleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
